/**
 * Professional PDF Report Generator
 * Creates well-organized, styled PDF compliance reports
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Project } from '@/types';

interface PDFReportData {
  project: Project;
  reportType: string;
  aiContent: string;
  summary: string;
  recommendations: string[];
  statistics: any;
  complianceScore: number;
  generatedBy: string;
  generatedAt: string;
}

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: typeof autoTable;
  }
}

/**
 * Generate professional PDF report
 */
export async function generatePDFReport(data: PDFReportData): Promise<Blob> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // Page dimensions
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (2 * margin);
  
  let yPosition = margin;

  // Helper function to add new page if needed
  const checkPageBreak = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      addHeader();
      return true;
    }
    return false;
  };

  // Header function
  const addHeader = () => {
    // Add logo/branding area (placeholder - can add actual logo)
    doc.setFillColor(79, 70, 229); // Brand primary color
    doc.rect(0, 0, pageWidth, 15, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('AccreditEx', margin, 10);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Healthcare Accreditation Management System', pageWidth - margin, 10, { align: 'right' });
    
    yPosition = 20;
  };

  // Footer function
  const addFooter = (pageNum: number, totalPages: number) => {
    doc.setTextColor(128, 128, 128);
    doc.setFontSize(8);
    doc.text(
      `Page ${pageNum} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(
      `Generated: ${new Date(data.generatedAt).toLocaleDateString()}`,
      margin,
      pageHeight - 10
    );
    doc.text(
      `Confidential`,
      pageWidth - margin,
      pageHeight - 10,
      { align: 'right' }
    );
  };

  // Add initial header
  addHeader();

  // Title Page
  yPosition = 60;
  
  // Report title
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  const reportTitle = getReportTitle(data.reportType);
  doc.text(reportTitle, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 15;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.text(data.project.name, pageWidth / 2, yPosition, { align: 'center' });
  
  // Status badge
  yPosition += 15;
  const complianceColor = getComplianceColor(data.complianceScore);
  doc.setFillColor(complianceColor.r, complianceColor.g, complianceColor.b);
  doc.roundedRect(pageWidth / 2 - 30, yPosition - 5, 60, 10, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`${data.complianceScore.toFixed(1)}% Compliant`, pageWidth / 2, yPosition + 2, { align: 'center' });
  
  // Metadata box
  yPosition += 25;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.5);
  doc.rect(margin, yPosition, contentWidth, 40);
  
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const metadataY = yPosition + 8;
  doc.text('Report Type:', margin + 5, metadataY);
  doc.setFont('helvetica', 'bold');
  doc.text(reportTitle, margin + 35, metadataY);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Generated By:', margin + 5, metadataY + 8);
  doc.setFont('helvetica', 'bold');
  doc.text(data.generatedBy, margin + 35, metadataY + 8);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Generated On:', margin + 5, metadataY + 16);
  doc.setFont('helvetica', 'bold');
  doc.text(new Date(data.generatedAt).toLocaleString(), margin + 35, metadataY + 16);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Project Status:', margin + 5, metadataY + 24);
  doc.setFont('helvetica', 'bold');
  doc.text(data.project.status, margin + 35, metadataY + 24);

  // Add watermark
  doc.setTextColor(240, 240, 240);
  doc.setFontSize(60);
  doc.setFont('helvetica', 'bold');
  doc.text('CONFIDENTIAL', pageWidth / 2, pageHeight / 2, {
    align: 'center',
    angle: 45
  });

  // New page for content
  doc.addPage();
  addHeader();
  yPosition = 30;

  // Executive Summary Section
  doc.setTextColor(79, 70, 229);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', margin, yPosition);
  
  yPosition += 8;
  doc.setDrawColor(79, 70, 229);
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  
  yPosition += 8;
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const summaryLines = doc.splitTextToSize(data.summary, contentWidth);
  doc.text(summaryLines, margin, yPosition);
  yPosition += (summaryLines.length * 5) + 10;

  // Key Metrics Table
  checkPageBreak(60);
  
  doc.setTextColor(79, 70, 229);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Key Compliance Metrics', margin, yPosition);
  yPosition += 8;

  autoTable(doc, {
    startY: yPosition,
    head: [['Metric', 'Value', 'Percentage']],
    body: [
      ['Total Standards', String(data.statistics.totalStandards), '100%'],
      ['Compliant', String(data.statistics.compliantStandards), `${((data.statistics.compliantStandards / data.statistics.totalStandards) * 100).toFixed(1)}%`],
      ['Partially Compliant', String(data.statistics.partiallyCompliantStandards), `${((data.statistics.partiallyCompliantStandards / data.statistics.totalStandards) * 100).toFixed(1)}%`],
      ['Non-Compliant', String(data.statistics.nonCompliantStandards), `${((data.statistics.nonCompliantStandards / data.statistics.totalStandards) * 100).toFixed(1)}%`],
      ['Not Applicable', String(data.statistics.notApplicableStandards), `${((data.statistics.notApplicableStandards / data.statistics.totalStandards) * 100).toFixed(1)}%`],
    ],
    theme: 'grid',
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [60, 60, 60]
    },
    alternateRowStyles: {
      fillColor: [245, 245, 250]
    },
    margin: { left: margin, right: margin }
  });

  yPosition = (doc as any).lastAutoTable.finalY + 15;

  // Quality Improvement Metrics Table
  checkPageBreak(50);
  
  doc.setTextColor(79, 70, 229);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Quality Improvement Metrics', margin, yPosition);
  yPosition += 8;

  autoTable(doc, {
    startY: yPosition,
    head: [['Category', 'Count', 'Status']],
    body: [
      ['Open CAPA Reports', String(data.statistics.openCAPAs), data.statistics.openCAPAs > 0 ? 'In Progress' : 'None'],
      ['Completed CAPAs', String(data.statistics.completedCAPAs), 'Closed'],
      ['Mock Surveys Conducted', String(data.statistics.mockSurveysCompleted), 'Complete'],
      ['Critical Findings', String(data.statistics.criticalFindings), data.statistics.criticalFindings > 0 ? 'Attention Required' : 'None'],
      ['Evidence Documents', String(data.statistics.evidenceDocuments), 'Uploaded'],
    ],
    theme: 'grid',
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [60, 60, 60]
    },
    alternateRowStyles: {
      fillColor: [245, 245, 250]
    },
    margin: { left: margin, right: margin }
  });

  yPosition = (doc as any).lastAutoTable.finalY + 15;

  // Process AI content sections
  checkPageBreak(30);
  const sections = parseAIContent(data.aiContent);
  
  for (const section of sections) {
    checkPageBreak(20);
    
    // Section heading
    doc.setTextColor(79, 70, 229);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(section.title, margin, yPosition);
    
    yPosition += 6;
    doc.setDrawColor(79, 70, 229);
    doc.setLineWidth(0.3);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    
    yPosition += 8;
    
    // Section content
    doc.setTextColor(60, 60, 60);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    const contentLines = doc.splitTextToSize(section.content, contentWidth);
    
    for (let i = 0; i < contentLines.length; i++) {
      checkPageBreak(8);
      doc.text(contentLines[i], margin, yPosition);
      yPosition += 5;
    }
    
    yPosition += 5;
  }

  // Strategic Recommendations Section
  if (data.recommendations.length > 0) {
    checkPageBreak(40);
    
    doc.setTextColor(220, 38, 38); // Red for importance
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Strategic Recommendations', margin, yPosition);
    
    yPosition += 6;
    doc.setDrawColor(220, 38, 38);
    doc.setLineWidth(0.3);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    
    yPosition += 10;
    
    doc.setTextColor(60, 60, 60);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    data.recommendations.forEach((rec, index) => {
      checkPageBreak(12);
      
      // Recommendation number circle
      doc.setFillColor(220, 38, 38);
      doc.circle(margin + 3, yPosition - 2, 3, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text(String(index + 1), margin + 3, yPosition, { align: 'center' });
      
      // Recommendation text
      doc.setTextColor(60, 60, 60);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const recLines = doc.splitTextToSize(rec, contentWidth - 10);
      doc.text(recLines, margin + 8, yPosition);
      
      yPosition += (recLines.length * 5) + 3;
    });
  }

  // Risk Assessment Badge
  checkPageBreak(30);
  yPosition += 10;
  
  doc.setTextColor(79, 70, 229);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Risk Assessment', margin, yPosition);
  yPosition += 10;
  
  const riskLevel = getRiskLevel(data.complianceScore);
  const riskColor = getRiskColor(riskLevel);
  
  doc.setFillColor(riskColor.r, riskColor.g, riskColor.b);
  doc.roundedRect(margin, yPosition, 60, 15, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Risk Level: ${riskLevel}`, margin + 30, yPosition + 9, { align: 'center' });
  
  // Add page numbers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(i, totalPages);
  }

  // Return PDF as blob
  return doc.output('blob');
}

/**
 * Get report title from type
 */
function getReportTitle(reportType: string): string {
  const titles: Record<string, string> = {
    complianceSummary: 'Compliance Summary Report',
    detailedCompliance: 'Detailed Compliance Report',
    executiveSummary: 'Executive Summary',
    capaAnalysis: 'CAPA Analysis Report'
  };
  return titles[reportType] || 'Compliance Report';
}

/**
 * Get compliance color based on score
 */
function getComplianceColor(score: number): { r: number; g: number; b: number } {
  if (score >= 85) return { r: 34, g: 197, b: 94 }; // Green
  if (score >= 70) return { r: 251, g: 191, b: 36 }; // Yellow
  return { r: 239, g: 68, b: 68 }; // Red
}

/**
 * Get risk level from compliance score
 */
function getRiskLevel(score: number): string {
  if (score >= 85) return 'LOW';
  if (score >= 70) return 'MEDIUM';
  return 'HIGH';
}

/**
 * Get risk color
 */
function getRiskColor(level: string): { r: number; g: number; b: number } {
  if (level === 'LOW') return { r: 34, g: 197, b: 94 }; // Green
  if (level === 'MEDIUM') return { r: 251, g: 191, b: 36 }; // Yellow
  return { r: 239, g: 68, b: 68 }; // Red
}

/**
 * Parse AI content into sections
 */
function parseAIContent(content: string): Array<{ title: string; content: string }> {
  const sections: Array<{ title: string; content: string }> = [];
  const lines = content.split('\n');
  
  let currentSection: { title: string; content: string } | null = null;
  
  for (const line of lines) {
    // Check for markdown headers
    const headerMatch = line.match(/^#{1,3}\s+(.+)$/);
    
    if (headerMatch) {
      // Save previous section
      if (currentSection && currentSection.content.trim()) {
        sections.push(currentSection);
      }
      
      // Start new section
      currentSection = {
        title: headerMatch[1].replace(/\*\*/g, '').trim(),
        content: ''
      };
    } else if (currentSection && line.trim()) {
      // Add to current section content
      currentSection.content += line.replace(/\*\*/g, '') + '\n';
    }
  }
  
  // Add last section
  if (currentSection && currentSection.content.trim()) {
    sections.push(currentSection);
  }
  
  return sections.filter(s => 
    !s.title.toLowerCase().includes('report') && 
    !s.title.toLowerCase().includes('project:') &&
    s.content.length > 20
  );
}

/**
 * Download PDF blob as file
 */
export function downloadPDF(blob: Blob, fileName: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
