// This file was generated by the AI to create the main application state store.

import { create } from 'zustand';
import {
    AppDocument, Department, Standard, AccreditationProgram, TrainingProgram,
    CustomCalendarEvent, Notification, AppSettings, Competency, Risk, IncidentReport,
    AuditPlan, Audit
} from '../types';
import { backendService } from '../services/BackendService';
import { useUserStore } from './useUserStore';

interface AppState {
    documents: AppDocument[];
    departments: Department[];
    standards: Standard[];
    accreditationPrograms: AccreditationProgram[];
    trainingPrograms: TrainingProgram[];
    userTrainingStatuses: { [userId: string]: any };
    certificates: any[];
    customEvents: CustomCalendarEvent[];
    notifications: Notification[];
    appSettings: AppSettings | null;
    competencies: Competency[];
    risks: Risk[];
    incidentReports: IncidentReport[];
    auditPlans: AuditPlan[];
    audits: Audit[];

    fetchAllData: () => Promise<void>;

    // Documents
    addDocument: (doc: AppDocument) => void;
    updateDocument: (doc: AppDocument) => Promise<void>;
    addControlledDocument: (data: { name: { en: string; ar: string }, type: AppDocument['type'] }) => Promise<void>;
    addProcessMap: (data: { name: { en: string; ar: string } }) => Promise<void>;
    deleteDocument: (docId: string) => Promise<void>;
    approveDocument: (docId: string, passwordAttempt: string, projectId?: string) => Promise<void>;

    // Departments
    addDepartment: (dept: Omit<Department, 'id'>) => Promise<void>;
    updateDepartment: (dept: Department) => Promise<void>;
    deleteDepartment: (deptId: string) => Promise<void>;

    // Programs & Standards
    addProgram: (program: Omit<AccreditationProgram, 'id'>) => Promise<void>;
    updateProgram: (program: AccreditationProgram) => Promise<void>;
    deleteProgram: (programId: string) => Promise<void>;
    addStandard: (standard: Omit<Standard, 'programId'> & { programId: string }) => Promise<void>;
    updateStandard: (standard: Standard) => Promise<void>;
    deleteStandard: (standardId: string) => Promise<void>;
    importStandards: (jsonContent: string, programId: string) => Promise<{ success: boolean; count: number; error?: string }>;

    // Training
    addTrainingProgram: (program: Omit<TrainingProgram, 'id'>) => Promise<void>;
    updateTrainingProgram: (program: TrainingProgram) => Promise<void>;
    deleteTrainingProgram: (programId: string) => Promise<void>;
    assignTraining: (data: { trainingId: string; userIds: string[]; departmentIds: string[]; dueDate?: string }) => Promise<void>;
    submitQuiz: (trainingId: string, answers: { [questionId: string]: number }) => Promise<{ score: number; passed: boolean; certificateId: string | null }>;

    // Competencies
    addCompetency: (comp: Omit<Competency, 'id'>) => Promise<void>;
    updateCompetency: (comp: Competency) => Promise<void>;
    deleteCompetency: (compId: string) => Promise<void>;

    // Risk & Incidents
    addRisk: (risk: Omit<Risk, 'id'>) => Promise<void>;
    updateRisk: (risk: Risk) => Promise<void>;
    deleteRisk: (riskId: string) => Promise<void>;
    addIncidentReport: (report: Omit<IncidentReport, 'id'>) => Promise<void>;
    updateIncidentReport: (report: IncidentReport) => Promise<void>;
    deleteIncidentReport: (reportId: string) => Promise<void>;

    // Audits
    addAuditPlan: (plan: Omit<AuditPlan, 'id'>) => Promise<void>;
    updateAuditPlan: (plan: AuditPlan) => Promise<void>;
    deleteAuditPlan: (planId: string) => Promise<void>;
    runAudit: (planId: string) => Promise<void>;

    addCustomEvent: (event: Omit<CustomCalendarEvent, 'id' | 'type'>) => Promise<void>;
    updateCustomEvent: (event: CustomCalendarEvent) => Promise<void>;
    deleteCustomEvent: (eventId: string) => Promise<void>;
    updateAppSettings: (settings: AppSettings) => Promise<void>;
    clearNotifications: () => void;
}

export const useAppStore = create<AppState>((set, get) => ({
    documents: [],
    departments: [],
    standards: [],
    accreditationPrograms: [],
    trainingPrograms: [],
    userTrainingStatuses: {},
    certificates: [],
    customEvents: [],
    notifications: [],
    appSettings: null,
    competencies: [],
    risks: [],
    incidentReports: [],
    auditPlans: [],
    audits: [],

    fetchAllData: async () => {
        const userId = useUserStore.getState().currentUser?.id;
        const data = {
            documents: backendService.getDocuments(),
            departments: backendService.getDepartments(),
            standards: backendService.getStandards(),
            accreditationPrograms: backendService.getAccreditationPrograms(),
            trainingPrograms: backendService.getTrainingPrograms(),
            userTrainingStatuses: backendService.getUserTrainingStatuses(),
            certificates: backendService.getCertificates(),
            customEvents: backendService.getCustomEvents(),
            notifications: userId ? backendService.getNotifications(userId) : [],
            appSettings: backendService.getAppSettings(),
            competencies: backendService.getCompetencies(),
            risks: backendService.getRisks(),
            incidentReports: backendService.getIncidentReports(),
            auditPlans: backendService.getAuditPlans(),
            audits: backendService.getAudits(),
        };
        set(data);
    },

    // Documents
    addDocument: (doc) => set(state => ({ documents: [...state.documents, doc] })),
    updateDocument: async (doc) => {
        const updated = await backendService.updateDocument(doc);
        set(state => ({ documents: state.documents.map(d => d.id === updated.id ? updated : d) }));
    },
    addControlledDocument: async (data) => {
        const newDoc = await backendService.addControlledDocument(data);
        set(state => ({ documents: [...state.documents, newDoc] }));
    },
    addProcessMap: async (data) => {
        const newDoc = await backendService.addProcessMap(data);
        set(state => ({ documents: [...state.documents, newDoc] }));
    },
    deleteDocument: async (docId) => {
        await backendService.deleteDocument(docId);
        set(state => ({ documents: state.documents.filter(d => d.id !== docId) }));
    },
    approveDocument: async (docId, passwordAttempt, projectId) => {
        const currentUser = useUserStore.getState().currentUser;
        if (!currentUser) return;
        const updatedDoc = await backendService.approveDocument(docId, currentUser.id, passwordAttempt, projectId);
        set(state => ({ documents: state.documents.map(d => d.id === updatedDoc.id ? updatedDoc : d) }));
    },

    // Departments
    addDepartment: async (dept) => {
        const newDept = await backendService.addDepartment(dept);
        set(state => ({ departments: [...state.departments, newDept] }));
    },
    updateDepartment: async (dept) => {
        const updated = await backendService.updateDepartment(dept);
        set(state => ({ departments: state.departments.map(d => d.id === updated.id ? updated : d) }));
    },
    deleteDepartment: async (deptId) => {
        await backendService.deleteDepartment(deptId);
        set(state => ({ departments: state.departments.filter(d => d.id !== deptId) }));
    },

    // Programs & Standards
    addProgram: async (program) => {
        const newProg = await backendService.addAccreditationProgram(program);
        set(state => ({ accreditationPrograms: [...state.accreditationPrograms, newProg] }));
    },
    updateProgram: async (program) => {
        const updated = await backendService.updateAccreditationProgram(program);
        set(state => ({ accreditationPrograms: state.accreditationPrograms.map(p => p.id === updated.id ? updated : p) }));
    },
    deleteProgram: async (programId) => {
        await backendService.deleteAccreditationProgram(programId);
        set(state => ({ accreditationPrograms: state.accreditationPrograms.filter(p => p.id !== programId) }));
    },
    addStandard: async (standard) => {
        const newStandard = await backendService.addStandard(standard);
        set(state => ({ standards: [...state.standards, newStandard] }));
    },
    updateStandard: async (standard) => {
        const updated = await backendService.updateStandard(standard);
        set(state => ({ standards: state.standards.map(s => s.standardId === updated.standardId ? updated : s) }));
    },
    deleteStandard: async (standardId) => {
        await backendService.deleteStandard(standardId);
        set(state => ({ standards: state.standards.filter(s => s.standardId !== standardId) }));
    },
    importStandards: async (jsonContent, programId) => {
        try {
            const newStandards = await backendService.importStandards(jsonContent, programId);
            set(state => ({ standards: [...state.standards, ...newStandards] }));
            return { success: true, count: newStandards.length };
        } catch (e: any) {
            return { success: false, count: 0, error: e.message };
        }
    },

    // Training
    addTrainingProgram: async (program) => {
        const newProg = await backendService.addTrainingProgram(program);
        set(state => ({ trainingPrograms: [...state.trainingPrograms, newProg] }));
    },
    updateTrainingProgram: async (program) => {
        const updated = await backendService.updateTrainingProgram(program);
        set(state => ({ trainingPrograms: state.trainingPrograms.map(p => p.id === updated.id ? updated : p) }));
    },
    deleteTrainingProgram: async (programId) => {
        await backendService.deleteTrainingProgram(programId);
        set(state => ({ trainingPrograms: state.trainingPrograms.filter(p => p.id !== programId) }));
    },
    assignTraining: async (data) => {
        await backendService.assignTraining(data);
        // Re-fetch users to see updated assignments
        useUserStore.getState().fetchUsers();
    },
    submitQuiz: async (trainingId, answers) => {
        const currentUser = useUserStore.getState().currentUser;
        if (!currentUser) throw new Error("No user logged in");
        const { result, newCertificate } = await backendService.submitQuiz(currentUser.id, trainingId, answers);

        const currentStatuses = get().userTrainingStatuses;
        const userStatuses = currentStatuses[currentUser.id] || {};

        set({
            userTrainingStatuses: {
                ...currentStatuses,
                [currentUser.id]: {
                    ...userStatuses,
                    [trainingId]: result
                }
            }
        });

        if (newCertificate) {
            set(state => ({ certificates: [...state.certificates, newCertificate] }));
        }

        return { ...result, certificateId: newCertificate?.id || null };
    },

    // Competencies
    addCompetency: async (comp) => {
        const newComp = await backendService.addCompetency(comp);
        set(state => ({ competencies: [...state.competencies, newComp] }));
    },
    updateCompetency: async (comp) => {
        const updated = await backendService.updateCompetency(comp);
        set(state => ({ competencies: state.competencies.map(c => c.id === updated.id ? updated : c) }));
    },
    deleteCompetency: async (compId) => {
        await backendService.deleteCompetency(compId);
        set(state => ({ competencies: state.competencies.filter(c => c.id !== compId) }));
    },

    // Risk & Incidents
    addRisk: async (risk) => {
        const newRisk = await backendService.addRisk(risk);
        set(state => ({ risks: [...state.risks, newRisk] }));
    },
    updateRisk: async (risk) => {
        const updated = await backendService.updateRisk(risk);
        set(state => ({ risks: state.risks.map(r => r.id === updated.id ? updated : r) }));
    },
    deleteRisk: async (riskId) => {
        await backendService.deleteRisk(riskId);
        set(state => ({ risks: state.risks.filter(r => r.id !== riskId) }));
    },
    addIncidentReport: async (report) => {
        const newReport = await backendService.addIncidentReport(report);
        set(state => ({ incidentReports: [...state.incidentReports, newReport] }));
    },
    updateIncidentReport: async (report) => {
        const updated = await backendService.updateIncidentReport(report);
        set(state => ({ incidentReports: state.incidentReports.map(r => r.id === updated.id ? updated : r) }));
    },
    deleteIncidentReport: async (reportId) => {
        await backendService.deleteIncidentReport(reportId);
        set(state => ({ incidentReports: state.incidentReports.filter(r => r.id !== reportId) }));
    },

    // Audits
    addAuditPlan: async (plan) => {
        const newPlan = await backendService.addAuditPlan(plan);
        set(state => ({ auditPlans: [...state.auditPlans, newPlan] }));
    },
    updateAuditPlan: async (plan) => {
        const updated = await backendService.updateAuditPlan(plan);
        set(state => ({ auditPlans: state.auditPlans.map(p => p.id === updated.id ? updated : p) }));
    },
    deleteAuditPlan: async (planId) => {
        await backendService.deleteAuditPlan(planId);
        set(state => ({ auditPlans: state.auditPlans.filter(p => p.id !== planId) }));
    },
    runAudit: async (planId) => {
        const newAudit = await backendService.runAudit(planId);
        set(state => ({ audits: [...state.audits, newAudit] }));
        // Potentially add a notification here
    },
    // Calendar Events
    addCustomEvent: async (data) => {
        const newEvent = await backendService.addCustomEvent(data);
        set(state => ({ customEvents: [...state.customEvents, newEvent] }));
    },
    updateCustomEvent: async (event) => {
        const updated = await backendService.updateCustomEvent(event);
        set(state => ({ customEvents: state.customEvents.map(e => e.id === updated.id ? updated : e) }));
    },
    deleteCustomEvent: async (eventId) => {
        await backendService.deleteCustomEvent(eventId);
        set(state => ({ customEvents: state.customEvents.filter(e => e.id !== eventId) }));
    },
    // App Settings
    updateAppSettings: async (settings) => {
        await backendService.updateAppSettings(settings);
        set({ appSettings: settings });
    },
    clearNotifications: () => {
        set({ notifications: [] });
    },
}));