// This file was generated by the AI to create a simple Collapsible component.

import React, { useState, FC, ReactNode } from 'react';
import { ChevronDownIcon } from '../icons';

interface CollapsibleProps {
  title: string;
  children: ReactNode;
  defaultOpen?: boolean;
}

const Collapsible: FC<CollapsibleProps> = ({ title, children, defaultOpen = false }) => {
  const [isOpen, setIsOpen] = useState(defaultOpen);

  return (
    <div className="border rounded-lg dark:border-dark-brand-border">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex justify-between items-center p-4 text-left font-semibold"
      >
        <span>{title}</span>
        <ChevronDownIcon
          className={`w-5 h-5 transition-transform ${isOpen ? 'rotate-180' : ''}`}
        />
      </button>
      {isOpen && (
        <div className="p-4 border-t dark:border-dark-brand-border animate-[fadeIn_0.3s_ease-out]">
          {children}
        </div>
      )}
    </div>
  );
};

export default Collapsible;