// This file was generated by the AI to create a new Task Status Distribution chart.

import React, { useMemo } from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Cell,
} from "recharts";
import { ChecklistItem, ComplianceStatus } from "@/types";
import { useTranslation } from "@/hooks/useTranslation";
import { useTheme } from "@/components/common/ThemeProvider";
import { statusToTranslationKey } from "@/utils/complianceUtils";
import {
  CHART_COLORS,
  getChartTheme,
  ChartTooltip,
  CHART_ANIMATION,
} from "@/utils/chartTheme";
interface Props {
  checklistItems: ChecklistItem[];
}

const TaskStatusDistributionChart: React.FC<Props> = ({ checklistItems }) => {
  const { t } = useTranslation();
  const { theme } = useTheme();

  const data = useMemo(() => {
    const statusCounts = checklistItems.reduce(
      (acc, item) => {
        acc[item.status] = (acc[item.status] || 0) + 1;
        return acc;
      },
      {} as Record<ComplianceStatus, number>,
    );

    return Object.entries(statusCounts).map(([name, value]) => ({
      name: t(statusToTranslationKey(name) as any),
      count: value,
    }));
  }, [checklistItems, t]);

  const COLORS: Record<string, string> = {
    [t("compliant")]: CHART_COLORS.compliance.compliant,
    [t("partiallyCompliant")]: CHART_COLORS.compliance.partiallyCompliant,
    [t("nonCompliant")]: CHART_COLORS.compliance.nonCompliant,
    [t("notApplicable")]: CHART_COLORS.compliance.notApplicable,
  };

  const ct = getChartTheme(theme);

  return (
    <div className="bg-brand-surface dark:bg-dark-brand-surface p-6 rounded-xl shadow-md border border-brand-border dark:border-dark-brand-border h-full flex flex-col">
      <h3 className="text-lg font-semibold mb-4 text-brand-text-primary dark:text-dark-brand-text-primary">
        {t("taskStatusDistribution")}
      </h3>
      {data.length > 0 ? (
        <div className="flex-grow min-h-0">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart
              data={data}
              layout="vertical"
              margin={{ top: 5, right: 20, left: 20, bottom: 5 }}
            >
              <CartesianGrid
                strokeDasharray="3 3"
                stroke={ct.gridStroke}
                horizontal={false}
              />
              <XAxis type="number" tick={ct.tickStyle} />
              <YAxis
                type="category"
                dataKey="name"
                width={80}
                tick={ct.tickStyle}
                tickLine={false}
              />
              <Tooltip
                content={<ChartTooltip />}
                cursor={{ fill: ct.cursorFill }}
              />
              <Bar
                dataKey="count"
                name={t("tasks")}
                barSize={20}
                animationDuration={CHART_ANIMATION.duration}
              >
                {data.map((entry, index) => (
                  <Cell
                    key={`cell-${index}`}
                    fill={COLORS[entry.name] || "#8884d8"}
                  />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
      ) : (
        <div className="flex items-center justify-center flex-grow">
          <p className="text-brand-text-secondary dark:text-dark-brand-text-secondary">
            {t("noDataAvailable")}
          </p>
        </div>
      )}
    </div>
  );
};

export default TaskStatusDistributionChart;
