// This file was generated by the AI to create the Risk Hub page.

import React, { useState } from 'react';
import { NavigationState } from '../types';
import { useTranslation } from '../hooks/useTranslation';
import { ExclamationTriangleIcon } from '../components/icons';
import { useAppStore } from '../stores/useAppStore';
import { useProjectStore } from '../stores/useProjectStore';
import { useUserStore } from '../stores/useUserStore';
import RiskRegisterTab from '../components/risk/RiskRegisterTab';
import IncidentReportingTab from '../components/risk/IncidentReportingTab';
import CapaReportsTab from '../components/risk/CapaReportsTab';
import EffectivenessChecksTab from '../components/risk/EffectivenessChecksTab';

interface RiskHubPageProps {
  setNavigation: (state: NavigationState) => void;
}

type ActiveTab = 'register' | 'incidents' | 'capa' | 'effectiveness';

const RiskHubPage: React.FC<RiskHubPageProps> = ({ setNavigation }) => {
  const { t } = useTranslation();
  const [activeTab, setActiveTab] = useState<ActiveTab>('register');
  
  const { projects, updateCapa } = useProjectStore();
  const { users, currentUser } = useUserStore();
  const { 
    risks, incidentReports, trainingPrograms,
    addRisk, updateRisk, deleteRisk,
    addIncidentReport, updateIncidentReport, deleteIncidentReport
  } = useAppStore();
  
  const tabButtonClasses = (tabName: ActiveTab) => 
    `px-4 py-2 text-sm font-semibold rounded-t-lg border-b-2 transition-colors ${
        activeTab === tabName 
        ? 'border-brand-primary text-brand-primary' 
        : 'border-transparent text-brand-text-secondary dark:text-dark-brand-text-secondary hover:border-gray-300 dark:hover:border-gray-600'
    }`;

  if (!currentUser) return null;

  return (
    <div className="space-y-6">
      <div className="flex items-center space-x-3 rtl:space-x-reverse self-start">
        <ExclamationTriangleIcon className="h-8 w-8 text-brand-primary" />
        <div>
          <h1 className="text-3xl font-bold dark:text-dark-brand-text-primary">{t('riskHubTitle')}</h1>
          <p className="text-brand-text-secondary dark:text-dark-brand-text-secondary mt-1">{t('riskHubDescription')}</p>
        </div>
      </div>
      
      <div className="border-b border-gray-200 dark:border-dark-brand-border">
        <nav className="-mb-px flex space-x-4 rtl:space-x-reverse" aria-label="Tabs">
            <button onClick={() => setActiveTab('register')} className={tabButtonClasses('register')}>{t('riskRegister')}</button>
            <button onClick={() => setActiveTab('incidents')} className={tabButtonClasses('incidents')}>{t('incidentReporting')}</button>
            <button onClick={() => setActiveTab('capa')} className={tabButtonClasses('capa')}>{t('capaReports')}</button>
            <button onClick={() => setActiveTab('effectiveness')} className={tabButtonClasses('effectiveness')}>{t('effectivenessChecks')}</button>
        </nav>
      </div>
      
      <div>
        {activeTab === 'register' && (
            <RiskRegisterTab
                risks={risks}
                users={users}
                trainingPrograms={trainingPrograms}
                currentUser={currentUser}
                onCreateRisk={addRisk}
                onUpdateRisk={updateRisk}
                onDeleteRisk={deleteRisk}
            />
        )}
        {activeTab === 'incidents' && (
            <IncidentReportingTab
                incidentReports={incidentReports}
                users={users}
                currentUser={currentUser}
                trainingPrograms={trainingPrograms}
                onCreate={addIncidentReport}
                onUpdate={updateIncidentReport}
                onDelete={deleteIncidentReport}
                onCreateCapa={useProjectStore.getState().createCapaReport}
            />
        )}
        {activeTab === 'capa' && <CapaReportsTab projects={projects} users={users} />}
        {activeTab === 'effectiveness' && <EffectivenessChecksTab projects={projects} onUpdateCapa={updateCapa} />}
      </div>
    </div>
  );
};

export default RiskHubPage;
