// This file was generated by the AI to create a new CAPA Root Cause chart.

import React, { useMemo } from 'react';
import { PieChart, Pie, Cell, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { Project } from '../../types';
import { useTranslation } from '../../hooks/useTranslation';
import { useTheme } from '../common/ThemeProvider';

interface Props {
  projects: Project[];
}

const CapaRootCauseChart: React.FC<Props> = ({ projects }) => {
  const { t } = useTranslation();
  const { theme } = useTheme();

  const data = useMemo(() => {
    const rootCauseCounts = projects.flatMap(p => p.capaReports)
      .reduce((acc, capa) => {
        const category = capa.rootCauseCategory || 'other';
        acc[category] = (acc[category] || 0) + 1;
        return acc;
      }, {} as Record<string, number>);
      
    return Object.entries(rootCauseCounts).map(([key, value]) => ({
      name: t(key as any),
      value,
    }));
  }, [projects, t]);
  
  const totalCapas = useMemo(() => data.reduce((sum, entry) => sum + entry.value, 0), [data]);

  const COLORS = ['#4f46e5', '#f97316', '#22c55e', '#ef4444', '#64748b'];
  const tooltipStyle = {
    borderRadius: '0.5rem',
    background: theme === 'dark' ? 'rgba(15, 23, 42, 0.8)' : 'rgba(255, 255, 255, 0.8)',
    backdropFilter: 'blur(4px)',
    border: `1px solid ${theme === 'dark' ? '#1e293b' : '#e2e8f0'}`,
  };

  return (
    <div className="bg-brand-surface dark:bg-dark-brand-surface p-6 rounded-xl shadow-md border border-brand-border dark:border-dark-brand-border h-full flex flex-col">
      <h3 className="text-lg font-semibold mb-4 text-brand-text-primary dark:text-dark-brand-text-primary">{t('capaRootCause')}</h3>
      {totalCapas > 0 ? (
        <div className="flex-grow min-h-0">
          <ResponsiveContainer width="100%" height="100%">
            <PieChart>
              <Pie data={data} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius="60%" outerRadius="80%" paddingAngle={5}>
                {data.map((entry, index) => <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />)}
              </Pie>
              <Tooltip contentStyle={tooltipStyle} />
              <Legend wrapperStyle={{ fontSize: '12px' }} layout="vertical" align="right" verticalAlign="middle" />
              <text x="50%" y="50%" textAnchor="middle" dominantBaseline="middle" fill={theme === 'dark' ? '#e2e8f0' : '#0f172a'} fontSize="28" fontWeight="bold">
                  {totalCapas}
              </text>
              <text x="50%" y="50%" dy={22} textAnchor="middle" fill={theme === 'dark' ? '#94a3b8' : '#64748b'} fontSize="12">
                  {t('capaReports')}
              </text>
            </PieChart>
          </ResponsiveContainer>
        </div>
      ) : <div className="flex items-center justify-center flex-grow"><p className="text-brand-text-secondary dark:text-dark-brand-text-secondary">{t('noDataAvailable')}</p></div>}
    </div>
  );
};

export default CapaRootCauseChart;