// This file was generated by the AI to create a new, enhanced KPI card.

import React, { FC } from 'react';
import { RadialBarChart, RadialBar, PolarAngleAxis, ResponsiveContainer } from 'recharts';
import { useTheme } from '../common/ThemeProvider';

interface KpiCardProps {
    title: string;
    value: number; // e.g., 85 for 85%
    total: number;
    completed: number;
    description: string;
    color: string; // hex color e.g., '#4f46e5'
}

const KpiCard: FC<KpiCardProps> = ({ title, value, total, completed, description, color }) => {
  const { theme } = useTheme();
  const data = [{ name: title, value }];

  return (
    <div className="bg-brand-surface dark:bg-dark-brand-surface p-5 rounded-xl shadow-lg border border-brand-border dark:border-dark-brand-border flex flex-col justify-between transition-all hover:shadow-xl hover:-translate-y-1">
      <div className="flex justify-between items-start">
        <p className="text-brand-text-secondary dark:text-dark-brand-text-secondary text-sm font-semibold">{title}</p>
        <div className="w-20 h-20 -mt-4 -mr-2">
            <ResponsiveContainer width="100%" height="100%">
                <RadialBarChart 
                    innerRadius="70%" 
                    outerRadius="100%" 
                    data={data} 
                    startAngle={90} 
                    endAngle={-270}
                >
                    <PolarAngleAxis type="number" domain={[0, 100]} angleAxisId={0} tick={false} />
                    <RadialBar 
                        background={{ fill: theme === 'dark' ? '#334155' : '#e2e8f0' }} 
                        dataKey="value" 
                        cornerRadius={10} 
                        fill={color} 
                        angleAxisId={0}
                    />
                </RadialBarChart>
            </ResponsiveContainer>
        </div>
      </div>
      <div className="-mt-12">
        <p className="text-4xl font-bold text-brand-text-primary dark:text-dark-brand-text-primary">{value}<span className="text-2xl text-brand-text-secondary dark:text-dark-brand-text-secondary">%</span></p>
        <p className="text-sm text-brand-text-secondary dark:text-dark-brand-text-secondary mt-1">
            <span className="font-semibold text-brand-text-primary dark:text-dark-brand-text-primary">{completed}</span>
            <span> / {total} {description}</span>
        </p>
      </div>
    </div>
  );
};

export default KpiCard;