// This file was generated by the AI to create the Data Settings page.

import React, { useState } from 'react';
import { useTranslation } from '../../hooks/useTranslation';
import SettingsCard from './SettingsCard';
import { backendService } from '../../services/BackendService';
import ConfirmationModal from '../common/ConfirmationModal';
import { useToast } from '../../hooks/useToast';

const DataSettingsPage: React.FC = () => {
    const { t } = useTranslation();
    const toast = useToast();
    const [isResetModalOpen, setIsResetModalOpen] = useState(false);

    const handleExport = () => {
        const data = backendService.exportAllData();
        const blob = new Blob([data], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `accreditex_backup_${new Date().toISOString().split('T')[0]}.json`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        toast.success("Data exported successfully!");
    };
    
    const handleImport = (event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = async (e) => {
                try {
                    const content = e.target?.result as string;
                    await backendService.importAllData(content);
                    toast.success("Data imported successfully! The application will now reload.");
                    setTimeout(() => window.location.reload(), 1500);
                } catch (error) {
                    toast.error("Failed to import data. Please check file format.");
                    console.error("Import failed:", error);
                }
            };
            reader.readAsText(file);
        }
    };
    
    const handleReset = async () => {
        await backendService.resetApplication();
        setIsResetModalOpen(false);
        toast.success("Application has been reset. Reloading...");
        setTimeout(() => window.location.reload(), 1500);
    };

    return (
        <>
            <div className="space-y-6">
                <SettingsCard 
                    title={t('backupAndRestore')} 
                    description={t('backupAndRestoreDescription')}
                >
                    <div className="flex flex-col sm:flex-row gap-4">
                        <button onClick={handleExport} className="w-full sm:w-auto bg-white dark:bg-gray-700 py-2 px-4 border border-gray-300 dark:border-gray-500 rounded-md shadow-sm text-sm font-medium hover:bg-gray-50 dark:hover:bg-gray-600">
                            {t('exportButton')}
                        </button>
                        <label className="w-full sm:w-auto cursor-pointer bg-white dark:bg-gray-700 py-2 px-4 border border-gray-300 dark:border-gray-500 rounded-md shadow-sm text-sm font-medium hover:bg-gray-50 dark:hover:bg-gray-600 text-center">
                            {t('importData')}
                            <input type="file" className="hidden" accept=".json" onChange={handleImport} />
                        </label>
                    </div>
                </SettingsCard>
                
                <SettingsCard title={t('dangerZone')} description={t('dangerZoneDescription')}>
                    <div className="flex justify-between items-center p-4 border border-red-300 dark:border-red-700 rounded-lg bg-red-50 dark:bg-red-900/20">
                        <div>
                            <p className="font-semibold text-red-800 dark:text-red-200">{t('resetApplication')}</p>
                            <p className="text-sm text-red-700 dark:text-red-300">{t('resetApplicationDescription')}</p>
                        </div>
                        <button onClick={() => setIsResetModalOpen(true)} className="bg-red-600 text-white px-4 py-2 rounded-md hover:bg-red-700 font-semibold text-sm">
                            {t('resetApp')}
                        </button>
                    </div>
                </SettingsCard>
            </div>
            
            <ConfirmationModal
                isOpen={isResetModalOpen}
                onClose={() => setIsResetModalOpen(false)}
                onConfirm={handleReset}
                title={t('resetApplication')}
                message={t('resetApplicationConfirmation')}
                confirmationText="RESET"
            />
        </>
    );
};

export default DataSettingsPage;
